### ISSUE TITLE
ReadTheOrg - TOC Alignment 

### ISSUE THREAD

**Issue by yitang** [fniessen/org-html-themes#19]
Hi, I like the way that the TOC has indentations to indicate the headline levels. 

The default TOC has right alignment, it feel it's hard to navigate to a specific date, as shown in the image. I wonder if there is an easy way to align the TOC to the left? 

![image](https://cloud.githubusercontent.com/assets/6054101/9132032/63eb5626-3ce8-11e5-860d-678088e42607.png)

**Comment by fniessen** [comment]
The default TOC has left alignment -- I don't understand how you get something else...

Which version of the CSS do you use: a local file (Git sandbox) or the CSS deployed on my Pirilampo Web site?

Is it like that with all your documents?  Can you send an Minimal Working Example?

**Comment by yitang** [comment]
Hi, I think this minimal working example can answer all the questions. 

```
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

#+options: toc:t

* H1
[2015-08-07 Fri 14:39]
** H2-1
[2015-08-07 Fri 14:39]
** H2-2
[2015-08-07 Fri 14:39]
```

and I get 

![image](https://cloud.githubusercontent.com/assets/6054101/9137006/ce992f00-3d12-11e5-940d-9c54b863f425.png)

I also include the HTML source code if it helps

```

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title></title>
<!-- 2015-08-07 Fri 14:41 -->
<meta  http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta  name="generator" content="Org-mode" />
<style type="text/css">
 <!--/*--><![CDATA[/*><!--*/
  .title  { text-align: center; }
  .todo   { font-family: monospace; color: red; }
  .done   { font-family: monospace; color: green; }
  .priority { font-family: monospace; color: orange; }
  .tag    { background-color: #eee; font-family: monospace;
            padding: 2px; font-size: 80%; font-weight: normal; }
  .timestamp { color: #bebebe; }
  .timestamp-kwd { color: #5f9ea0; }
  .right  { margin-left: auto; margin-right: 0px;  text-align: right; }
  .left   { margin-left: 0px;  margin-right: auto; text-align: left; }
  .center { margin-left: auto; margin-right: auto; text-align: center; }
  .underline { text-decoration: underline; }
  #postamble p, #preamble p { font-size: 90%; margin: .2em; }
  p.verse { margin-left: 3%; }
  pre {
    border: 1px solid #ccc;
    box-shadow: 3px 3px 3px #eee;
    padding: 8pt;
    font-family: monospace;
    overflow: auto;
    margin: 1.2em;
  }
  pre.src {
    position: relative;
    overflow: visible;
    padding-top: 1.2em;
  }
  pre.src:before {
    display: none;
    position: absolute;
    background-color: white;
    top: -10px;
    right: 10px;
    padding: 3px;
    border: 1px solid black;
  }
  pre.src:hover:before { display: inline;}
  pre.src-sh:before    { content: 'sh'; }
  pre.src-bash:before  { content: 'sh'; }
  pre.src-emacs-lisp:before { content: 'Emacs Lisp'; }
  pre.src-R:before     { content: 'R'; }
  pre.src-perl:before  { content: 'Perl'; }
  pre.src-java:before  { content: 'Java'; }
  pre.src-sql:before   { content: 'SQL'; }

  table { border-collapse:collapse; }
  caption.t-above { caption-side: top; }
  caption.t-bottom { caption-side: bottom; }
  td, th { vertical-align:top;  }
  th.right  { text-align: center;  }
  th.left   { text-align: center;   }
  th.center { text-align: center; }
  td.right  { text-align: right;  }
  td.left   { text-align: left;   }
  td.center { text-align: center; }
  dt { font-weight: bold; }
  .footpara:nth-child(2) { display: inline; }
  .footpara { display: block; }
  .footdef  { margin-bottom: 1em; }
  .figure { padding: 1em; }
  .figure p { text-align: center; }
  .inlinetask {
    padding: 10px;
    border: 2px solid gray;
    margin: 10px;
    background: #ffffcc;
  }
  #org-div-home-and-up
   { text-align: right; font-size: 70%; white-space: nowrap; }
  textarea { overflow-x: auto; }
  .linenr { font-size: smaller }
  .code-highlighted { background-color: #ffff00; }
  .org-info-js_info-navigation { border-style: none; }
  #org-info-js_console-label
    { font-size: 10px; font-weight: bold; white-space: nowrap; }
  .org-info-js_search-highlight
    { background-color: #ffff00; color: #000000; font-weight: bold; }
  /*]]>*/-->
</style>
<link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
<link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
<script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>
<script type="text/javascript">
/*
@licstart  The following is the entire license notice for the
JavaScript code in this tag.

Copyright (C) 2012-2013 Free Software Foundation, Inc.

The JavaScript code in this tag is free software: you can
redistribute it and/or modify it under the terms of the GNU
General Public License (GNU GPL) as published by the Free Software
Foundation, either version 3 of the License, or (at your option)
any later version.  The code is distributed WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.

As additional permission under GNU GPL version 3 section 7, you
may distribute non-source (e.g., minimized or compacted) forms of
that code without the copy of the GNU GPL normally required by
section 4, provided you include this license notice and a URL
through which recipients can access the Corresponding Source.


@licend  The above is the entire license notice
for the JavaScript code in this tag.
*/
<!--/*--><![CDATA[/*><!--*/
 function CodeHighlightOn(elem, id)
 {
   var target = document.getElementById(id);
   if(null != target) {
     elem.cacheClassElem = elem.className;
     elem.cacheClassTarget = target.className;
     target.className = "code-highlighted";
     elem.className   = "code-highlighted";
   }
 }
 function CodeHighlightOff(elem, id)
 {
   var target = document.getElementById(id);
   if(elem.cacheClassElem)
     elem.className = elem.cacheClassElem;
   if(elem.cacheClassTarget)
     target.className = elem.cacheClassTarget;
 }
/*]]>*///-->
</script>
</head>
<body>
<div id="preamble" class="status">
<a name="top" id="top"></a>
</div>
<div id="content">
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#sec-1">1. H1</a>
<ul>
<li><a href="#sec-1-1">1.1. H2-1</a></li>
<li><a href="#sec-1-2">1.2. H2-2</a></li>
</ul>
</li>
</ul>
</div>
</div>

<div id="outline-container-sec-1" class="outline-2">
<h2 id="sec-1"><span class="section-number-2">1</span> H1</h2>
<div class="outline-text-2" id="text-1">
<p>

</p>
</div>
<div id="outline-container-sec-1-1" class="outline-3">
<h3 id="sec-1-1"><span class="section-number-3">1.1</span> H2-1</h3>
<div class="outline-text-3" id="text-1-1">
<p>

</p>
</div>
</div>
<div id="outline-container-sec-1-2" class="outline-3">
<h3 id="sec-1-2"><span class="section-number-3">1.2</span> H2-2</h3>
<div class="outline-text-3" id="text-1-2">
<p>

</p>
</div>
</div>
</div>
</div>
<div id="postamble" class="status">

<style type="text/css">
.back-to-top {
    position: fixed;
    bottom: 2em;
    right: 0px;
    text-decoration: none;
    color: #000000;
    background-color: rgba(235, 235, 235, 0.80);
    font-size: 12px;
    padding: 1em;
    display: none;
}
.back-to-top:hover {    
    background-color: rgba(135, 135, 135, 0.50);
}
</style>
<div class="back-to-top">
<a href="#top">Back to top</a> | <a href="mailto:yi.tang.uk@me.com">E-mail me</a>
</div>
<script type="text/javascript">
    var offset = 220;
    var duration = 500;
    jQuery(window).scroll(function() {
        if (jQuery(this).scrollTop() > offset) {
            jQuery('.back-to-top').fadeIn(duration);
        } else {
            jQuery('.back-to-top').fadeOut(duration);
        }
    });
</script>
</div>
</body>
</html>
```

**Comment by player1537** [comment]
I had a little bit of time and looked into this, and it seems to be related to [this line](https://github.com/fniessen/org-html-themes/blob/62b8f5813541c347fded7b7540b135b3d77041eb/styles/readtheorg/css/readtheorg.css#L729), which specifies that the `direction` should be `rtl` for the `#table-of-contents` element. A simple fix would be to simply comment out that line and see if that gives the expected output for you (it seems fine from this example, but I'm not sure exactly how you want it to look).

**Comment by yitang** [comment]
Hi, thanks for looking into this. I am expecting the default setting which
is the left alignment as Fabrice points out.

I am using the remote version (link to Pirilampo website), maybe I will
try the local version and comment out the line and see. 

player1537 @ 2015-08-10 18:10 BST:

> I had a little bit of time and looked into this, and it seems to be related to this line, which specifies that the direction should be rtl for the #table-of-contents element. A simple fix would be to simply
> comment out that line and see if that gives the expected output for you (it seems fine from this example, but I'm not sure exactly how you want it to look).
>
> —
> Reply to this email directly or view it on GitHub.

-- 
唐毅 (Yi Tang)
Email: yi.tang.uk@me.com

**Comment by fniessen** [comment]
Sorry for my lack of time. Thanks a lot at @player1537 to have looked into this. I've pushed the change he advices (commit 3282602). Please test and report. I'll put it straight away onto Pirilampo.org as well.

**Comment by fniessen** [comment]
Deployed on Pirilampo.

**Comment by yitang** [comment]
@fniessen 

I still have the right alignment, and in the http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css file, the `#table-of-contents{` block still have 

    direction: rtl;
    height:100%;
    background:#343131;

Am I using the wrong CSS file? I copied the settings directly from the README.md.

**Comment by fniessen** [comment]
When I click on the above link, I only find one occurrence of "direction" instead of two (as before my deletion). See http://screencast.com/t/8cevpnI1.

Don't you have to empty your browser cache or so?

**Comment by yitang** [comment]
It works as expected after clean the browser cache. 

It looks neat! 

Thanks! 

![image](https://cloud.githubusercontent.com/assets/6054101/9195149/7e96cb8a-4018-11e5-8518-c948782b8889.png)

**Comment by fniessen** [comment]
Thanks again to @player1537!
